[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "feminicidios-bolivia"
version = "0.1.0"
dependencies = [
    "scrapy",
    "mongoengine",
    "curl_cffi",
    "python-dotenv",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["models*", "utils*", "scrapers*"]
